// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package simpletracker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCalendarsRequest struct {
	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Maximum number of calendar summaries per response page.
	MaxResults *wrappers.Int32Value `protobuf:"bytes,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	// This is a serialized version of ListCalendarsRequestNextToken. This token must be
	// opaque to clients and not deserializable to a ListCalendarsRequestNextToken. Servers
	// will probably encrypt ListCalendarsRequestNextToken. Clients must simply pass in a
	// received next_token into here.
	NextToken            *wrappers.BytesValue `protobuf:"bytes,4,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListCalendarsRequest) Reset()         { *m = ListCalendarsRequest{} }
func (m *ListCalendarsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsRequest) ProtoMessage()    {}
func (*ListCalendarsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *ListCalendarsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsRequest.Unmarshal(m, b)
}
func (m *ListCalendarsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsRequest.Marshal(b, m, deterministic)
}
func (m *ListCalendarsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsRequest.Merge(m, src)
}
func (m *ListCalendarsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsRequest.Size(m)
}
func (m *ListCalendarsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsRequest proto.InternalMessageInfo

func (m *ListCalendarsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListCalendarsRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ListCalendarsRequest) GetMaxResults() *wrappers.Int32Value {
	if m != nil {
		return m.MaxResults
	}
	return nil
}

func (m *ListCalendarsRequest) GetNextToken() *wrappers.BytesValue {
	if m != nil {
		return m.NextToken
	}
	return nil
}

type ListCalendarsRequestNextToken struct {
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// The user ID inside the token must not be used for authorization purposes. Rather you first
	// authorize the request parameters, and then compare to the inner user_id.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The session ID inside the token must not be used for authorization purposes. Rather you first
	// authorize the request parameters, and then compare to the inner session_id.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Thiis is what a server wants to use for some other service call as a pagination token.
	NextTokenInner *wrappers.StringValue `protobuf:"bytes,4,opt,name=next_token_inner,json=nextTokenInner,proto3" json:"next_token_inner,omitempty"`
	// Pagination tokens can expire to prevent indefinite re-use.
	ExpiryEpochSeconds   int32    `protobuf:"varint,5,opt,name=expiryEpochSeconds,proto3" json:"expiryEpochSeconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCalendarsRequestNextToken) Reset()         { *m = ListCalendarsRequestNextToken{} }
func (m *ListCalendarsRequestNextToken) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsRequestNextToken) ProtoMessage()    {}
func (*ListCalendarsRequestNextToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *ListCalendarsRequestNextToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsRequestNextToken.Unmarshal(m, b)
}
func (m *ListCalendarsRequestNextToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsRequestNextToken.Marshal(b, m, deterministic)
}
func (m *ListCalendarsRequestNextToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsRequestNextToken.Merge(m, src)
}
func (m *ListCalendarsRequestNextToken) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsRequestNextToken.Size(m)
}
func (m *ListCalendarsRequestNextToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsRequestNextToken.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsRequestNextToken proto.InternalMessageInfo

func (m *ListCalendarsRequestNextToken) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ListCalendarsRequestNextToken) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListCalendarsRequestNextToken) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ListCalendarsRequestNextToken) GetNextTokenInner() *wrappers.StringValue {
	if m != nil {
		return m.NextTokenInner
	}
	return nil
}

func (m *ListCalendarsRequestNextToken) GetExpiryEpochSeconds() int32 {
	if m != nil {
		return m.ExpiryEpochSeconds
	}
	return 0
}

type ListCalendarsResponse struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CalendarSummaries    []*CalendarSummary   `protobuf:"bytes,2,rep,name=calendarSummaries,proto3" json:"calendarSummaries,omitempty"`
	NextToken            *wrappers.BytesValue `protobuf:"bytes,3,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListCalendarsResponse) Reset()         { *m = ListCalendarsResponse{} }
func (m *ListCalendarsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCalendarsResponse) ProtoMessage()    {}
func (*ListCalendarsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *ListCalendarsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCalendarsResponse.Unmarshal(m, b)
}
func (m *ListCalendarsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCalendarsResponse.Marshal(b, m, deterministic)
}
func (m *ListCalendarsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCalendarsResponse.Merge(m, src)
}
func (m *ListCalendarsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCalendarsResponse.Size(m)
}
func (m *ListCalendarsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCalendarsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCalendarsResponse proto.InternalMessageInfo

func (m *ListCalendarsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ListCalendarsResponse) GetCalendarSummaries() []*CalendarSummary {
	if m != nil {
		return m.CalendarSummaries
	}
	return nil
}

func (m *ListCalendarsResponse) GetNextToken() *wrappers.BytesValue {
	if m != nil {
		return m.NextToken
	}
	return nil
}

type CalendarSummary struct {
	// Format version field (not an OCC field).
	FormatVersion int32  `protobuf:"varint,1,opt,name=formatVersion,proto3" json:"formatVersion,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	// OCC version field.
	Version              int32    `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalendarSummary) Reset()         { *m = CalendarSummary{} }
func (m *CalendarSummary) String() string { return proto.CompactTextString(m) }
func (*CalendarSummary) ProtoMessage()    {}
func (*CalendarSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *CalendarSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalendarSummary.Unmarshal(m, b)
}
func (m *CalendarSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalendarSummary.Marshal(b, m, deterministic)
}
func (m *CalendarSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalendarSummary.Merge(m, src)
}
func (m *CalendarSummary) XXX_Size() int {
	return xxx_messageInfo_CalendarSummary.Size(m)
}
func (m *CalendarSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_CalendarSummary.DiscardUnknown(m)
}

var xxx_messageInfo_CalendarSummary proto.InternalMessageInfo

func (m *CalendarSummary) GetFormatVersion() int32 {
	if m != nil {
		return m.FormatVersion
	}
	return 0
}

func (m *CalendarSummary) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CalendarSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CalendarSummary) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *CalendarSummary) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type CalendarDetail struct {
	Summary              *CalendarSummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	HighlightedDays      []string         `protobuf:"bytes,2,rep,name=highlightedDays,proto3" json:"highlightedDays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CalendarDetail) Reset()         { *m = CalendarDetail{} }
func (m *CalendarDetail) String() string { return proto.CompactTextString(m) }
func (*CalendarDetail) ProtoMessage()    {}
func (*CalendarDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *CalendarDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalendarDetail.Unmarshal(m, b)
}
func (m *CalendarDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalendarDetail.Marshal(b, m, deterministic)
}
func (m *CalendarDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalendarDetail.Merge(m, src)
}
func (m *CalendarDetail) XXX_Size() int {
	return xxx_messageInfo_CalendarDetail.Size(m)
}
func (m *CalendarDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CalendarDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CalendarDetail proto.InternalMessageInfo

func (m *CalendarDetail) GetSummary() *CalendarSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *CalendarDetail) GetHighlightedDays() []string {
	if m != nil {
		return m.HighlightedDays
	}
	return nil
}

func init() {
	proto.RegisterType((*ListCalendarsRequest)(nil), "simpletracker.ListCalendarsRequest")
	proto.RegisterType((*ListCalendarsRequestNextToken)(nil), "simpletracker.ListCalendarsRequestNextToken")
	proto.RegisterType((*ListCalendarsResponse)(nil), "simpletracker.ListCalendarsResponse")
	proto.RegisterType((*CalendarSummary)(nil), "simpletracker.CalendarSummary")
	proto.RegisterType((*CalendarDetail)(nil), "simpletracker.CalendarDetail")
}

func init() {
	proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2)
}

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0xa7, 0x69, 0xf1, 0x44, 0x4d, 0x61, 0x55, 0x84, 0x05, 0xb4, 0x8a, 0x22, 0x0e,
	0x39, 0xb9, 0x52, 0x7a, 0x41, 0x88, 0x13, 0x2d, 0x48, 0x91, 0x2a, 0x0e, 0x1b, 0xd4, 0x6b, 0xb4,
	0xb5, 0xa7, 0xce, 0xaa, 0xf6, 0xae, 0xd9, 0x59, 0x43, 0xf2, 0x0c, 0x3c, 0x12, 0x2f, 0xc0, 0xab,
	0xf0, 0x16, 0xc8, 0x6b, 0xbb, 0xd4, 0x6e, 0x01, 0x71, 0xcb, 0xcc, 0xfc, 0x13, 0x7f, 0xff, 0xfc,
	0x0b, 0xe3, 0x58, 0x64, 0xa8, 0x12, 0x61, 0xa2, 0xc2, 0x68, 0xab, 0xd9, 0x3e, 0xc9, 0xbc, 0xc8,
	0xd0, 0x1a, 0x11, 0xdf, 0xa0, 0x79, 0x7e, 0x9c, 0x6a, 0x9d, 0x66, 0x78, 0xe2, 0x86, 0x57, 0xe5,
	0xf5, 0xc9, 0x57, 0x23, 0x8a, 0x02, 0x0d, 0xd5, 0xf2, 0xe9, 0x0f, 0x0f, 0x0e, 0x2f, 0x24, 0xd9,
	0xb3, 0xe6, 0x5f, 0x88, 0xe3, 0xe7, 0x12, 0xc9, 0xb2, 0x67, 0xb0, 0x57, 0x12, 0x9a, 0x95, 0x4c,
	0x42, 0x6f, 0xe2, 0xcd, 0x02, 0xbe, 0x5b, 0x95, 0x8b, 0x84, 0x1d, 0x01, 0x10, 0x12, 0x49, 0xad,
	0xaa, 0x99, 0xef, 0x66, 0x41, 0xd3, 0x59, 0x24, 0xec, 0x2d, 0x8c, 0x72, 0xb1, 0x59, 0x19, 0xa4,
	0x32, 0xb3, 0x14, 0x0e, 0x26, 0xde, 0x6c, 0x34, 0x7f, 0x11, 0xd5, 0x18, 0x51, 0x8b, 0x11, 0x2d,
	0x94, 0x3d, 0x9d, 0x5f, 0x8a, 0xac, 0x44, 0x0e, 0xb9, 0xd8, 0xf0, 0x5a, 0xce, 0xde, 0x00, 0x28,
	0xdc, 0xd8, 0x95, 0xd5, 0x37, 0xa8, 0xc2, 0x9d, 0x3f, 0x2c, 0xbf, 0xdb, 0x5a, 0xa4, 0x7a, 0x39,
	0xa8, 0xe4, 0x9f, 0x2a, 0xf5, 0xf4, 0xa7, 0x07, 0x47, 0x0f, 0x59, 0xf9, 0xd8, 0x2a, 0x58, 0x08,
	0x7b, 0x5f, 0xd0, 0x54, 0xa0, 0xce, 0xd3, 0x90, 0xb7, 0xe5, 0x5d, 0xb7, 0xfe, 0x5f, 0xdc, 0x0e,
	0xfa, 0x6e, 0x3f, 0xc0, 0xe3, 0xdf, 0xbc, 0x2b, 0xa9, 0x14, 0x9a, 0x86, 0xfa, 0xe5, 0x3d, 0xea,
	0xa5, 0x35, 0x52, 0xa5, 0x35, 0xf6, 0xf8, 0x16, 0x7b, 0x51, 0xed, 0xb0, 0x08, 0x18, 0x6e, 0x0a,
	0x69, 0xb6, 0xef, 0x0b, 0x1d, 0xaf, 0x97, 0x18, 0x6b, 0x95, 0x50, 0x38, 0x74, 0x90, 0x0f, 0x4c,
	0xa6, 0xdf, 0x3d, 0x78, 0xda, 0xf3, 0x4a, 0x85, 0x56, 0x84, 0x95, 0x47, 0x2a, 0xe3, 0x18, 0x89,
	0x9c, 0xc7, 0x47, 0xbc, 0x2d, 0xd9, 0x05, 0x3c, 0x69, 0xdf, 0xca, 0xb2, 0xcc, 0x73, 0x61, 0x24,
	0x52, 0xe8, 0x4f, 0x06, 0xb3, 0xd1, 0xfc, 0x38, 0xea, 0xbc, 0x9a, 0xe8, 0xac, 0xa3, 0xdb, 0xf2,
	0xfb, 0x8b, 0xbd, 0xa4, 0x06, 0xff, 0x95, 0xd4, 0x37, 0x0f, 0x0e, 0x7a, 0x9f, 0x60, 0xaf, 0x60,
	0xff, 0x5a, 0x9b, 0x5c, 0xd8, 0xcb, 0x4e, 0x42, 0xdd, 0x26, 0x1b, 0x83, 0x7f, 0x1b, 0x91, 0x2f,
	0x13, 0xc6, 0x60, 0x47, 0x89, 0x1c, 0x9b, 0x60, 0xdc, 0x6f, 0x76, 0x08, 0xc3, 0x58, 0x67, 0xba,
	0x0e, 0x22, 0xe0, 0x75, 0x71, 0x37, 0xfb, 0x61, 0x27, 0xfb, 0xa9, 0x85, 0x71, 0x0b, 0x73, 0x8e,
	0x56, 0xc8, 0x8c, 0xbd, 0xae, 0x6e, 0xe8, 0xb0, 0x1c, 0xc5, 0xbf, 0xef, 0xd3, 0xca, 0xd9, 0x0c,
	0x0e, 0xd6, 0x32, 0x5d, 0x67, 0x32, 0x5d, 0x5b, 0x4c, 0xce, 0xc5, 0xb6, 0xbe, 0x70, 0xc0, 0xfb,
	0xed, 0xab, 0x5d, 0x77, 0xa3, 0xd3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x72, 0xb3, 0xd3, 0x08,
	0xc0, 0x03, 0x00, 0x00,
}
