// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package simpletracker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserErrorReason int32

const (
	CreateUserErrorReason_CREATE_USER_ERROR_REASON_NO_ERROR              CreateUserErrorReason = 0
	CreateUserErrorReason_USER_ALREADY_EXISTS                            CreateUserErrorReason = 1
	CreateUserErrorReason_CREATE_USER_ERROR_REASON_INTERNAL_SERVER_ERROR CreateUserErrorReason = 2
)

var CreateUserErrorReason_name = map[int32]string{
	0: "CREATE_USER_ERROR_REASON_NO_ERROR",
	1: "USER_ALREADY_EXISTS",
	2: "CREATE_USER_ERROR_REASON_INTERNAL_SERVER_ERROR",
}

var CreateUserErrorReason_value = map[string]int32{
	"CREATE_USER_ERROR_REASON_NO_ERROR":              0,
	"USER_ALREADY_EXISTS":                            1,
	"CREATE_USER_ERROR_REASON_INTERNAL_SERVER_ERROR": 2,
}

func (x CreateUserErrorReason) String() string {
	return proto.EnumName(CreateUserErrorReason_name, int32(x))
}

func (CreateUserErrorReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type LoginUserErrorReason int32

const (
	LoginUserErrorReason_LOGIN_USER_ERROR_REASON_NO_ERROR              LoginUserErrorReason = 0
	LoginUserErrorReason_USER_MISSING_OR_PASSWORD_INCORRECT            LoginUserErrorReason = 1
	LoginUserErrorReason_LOGIN_USER_ERROR_REASON_INTERNAL_SERVER_ERROR LoginUserErrorReason = 2
)

var LoginUserErrorReason_name = map[int32]string{
	0: "LOGIN_USER_ERROR_REASON_NO_ERROR",
	1: "USER_MISSING_OR_PASSWORD_INCORRECT",
	2: "LOGIN_USER_ERROR_REASON_INTERNAL_SERVER_ERROR",
}

var LoginUserErrorReason_value = map[string]int32{
	"LOGIN_USER_ERROR_REASON_NO_ERROR":              0,
	"USER_MISSING_OR_PASSWORD_INCORRECT":            1,
	"LOGIN_USER_ERROR_REASON_INTERNAL_SERVER_ERROR": 2,
}

func (x LoginUserErrorReason) String() string {
	return proto.EnumName(LoginUserErrorReason_name, int32(x))
}

func (LoginUserErrorReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Success              bool                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorReason          CreateUserErrorReason `protobuf:"varint,2,opt,name=error_reason,json=errorReason,proto3,enum=simpletracker.CreateUserErrorReason" json:"error_reason,omitempty"`
	SessionId            string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetErrorReason() CreateUserErrorReason {
	if m != nil {
		return m.ErrorReason
	}
	return CreateUserErrorReason_CREATE_USER_ERROR_REASON_NO_ERROR
}

func (m *CreateUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorReason          LoginUserErrorReason `protobuf:"varint,2,opt,name=error_reason,json=errorReason,proto3,enum=simpletracker.LoginUserErrorReason" json:"error_reason,omitempty"`
	SessionId            string               `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginUserResponse) GetErrorReason() LoginUserErrorReason {
	if m != nil {
		return m.ErrorReason
	}
	return LoginUserErrorReason_LOGIN_USER_ERROR_REASON_NO_ERROR
}

func (m *LoginUserResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterEnum("simpletracker.CreateUserErrorReason", CreateUserErrorReason_name, CreateUserErrorReason_value)
	proto.RegisterEnum("simpletracker.LoginUserErrorReason", LoginUserErrorReason_name, LoginUserErrorReason_value)
	proto.RegisterType((*CreateUserRequest)(nil), "simpletracker.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "simpletracker.CreateUserResponse")
	proto.RegisterType((*LoginUserRequest)(nil), "simpletracker.LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "simpletracker.LoginUserResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x6d, 0x6b, 0xdb, 0x30,
	0x14, 0x85, 0xa7, 0x0c, 0xb6, 0xe4, 0xee, 0x05, 0x47, 0xdb, 0x98, 0x19, 0x0c, 0x32, 0x2f, 0x1b,
	0x23, 0x30, 0xc3, 0xb2, 0x5f, 0x60, 0x1c, 0x35, 0xb8, 0x75, 0xed, 0x72, 0xe5, 0xf4, 0xe5, 0x93,
	0x70, 0x13, 0x51, 0x4c, 0x1b, 0xcb, 0x95, 0x1c, 0xfa, 0x23, 0xfa, 0xb5, 0xb4, 0x7f, 0xb7, 0xc4,
	0x69, 0x5e, 0x5a, 0x92, 0x16, 0x4a, 0x3f, 0x1e, 0x9d, 0x7b, 0x1f, 0xce, 0x11, 0x5c, 0x80, 0x89,
	0x91, 0xda, 0x2d, 0xb4, 0x2a, 0x15, 0xfd, 0x60, 0xb2, 0x71, 0x71, 0x26, 0x4b, 0x9d, 0x0e, 0x4f,
	0xa5, 0x76, 0x76, 0xa0, 0xe9, 0x6b, 0x99, 0x96, 0x72, 0x60, 0xa4, 0x46, 0x79, 0x3e, 0x91, 0xa6,
	0xa4, 0xdf, 0xa0, 0x3e, 0xdd, 0xc8, 0xd3, 0xb1, 0xb4, 0x49, 0x8b, 0xfc, 0x69, 0xe0, 0x42, 0x4f,
	0xbd, 0x22, 0x35, 0xe6, 0x42, 0xe9, 0x91, 0x5d, 0x9b, 0x79, 0x73, 0xed, 0x5c, 0x13, 0xa0, 0xab,
	0x34, 0x53, 0xa8, 0xdc, 0x48, 0x6a, 0xc3, 0x5b, 0x33, 0x19, 0x0e, 0xa5, 0x31, 0x15, 0xad, 0x8e,
	0x73, 0x49, 0xfb, 0xf0, 0x5e, 0x6a, 0xad, 0xb4, 0xd0, 0x32, 0x35, 0x2a, 0xaf, 0x80, 0x1f, 0xbb,
	0x6d, 0xf7, 0x5e, 0x46, 0x77, 0x89, 0x64, 0xd3, 0x61, 0xac, 0x66, 0xf1, 0x9d, 0x5c, 0x0a, 0xfa,
	0x1d, 0xc0, 0x48, 0x63, 0x32, 0x95, 0x8b, 0x6c, 0x64, 0xbf, 0xae, 0x72, 0x35, 0xee, 0x5e, 0x82,
	0x91, 0xb3, 0x0d, 0x56, 0xa8, 0x4e, 0xb2, 0xfc, 0x25, 0x4a, 0x5e, 0x11, 0x68, 0xae, 0xc0, 0x9e,
	0xec, 0xb8, 0xb5, 0xb6, 0xe3, 0xcf, 0x07, 0x1d, 0x17, 0xc4, 0x67, 0x56, 0xec, 0x5c, 0x12, 0xf8,
	0xb2, 0xf6, 0xa3, 0xe8, 0x2f, 0xf8, 0xe1, 0x23, 0xf3, 0x12, 0x26, 0x06, 0x9c, 0xa1, 0x60, 0x88,
	0x31, 0x0a, 0x64, 0x1e, 0x8f, 0x23, 0x11, 0xc5, 0x33, 0x6d, 0xbd, 0xa2, 0x5f, 0xe1, 0x53, 0xe5,
	0x7b, 0x21, 0x32, 0xaf, 0x77, 0x24, 0xd8, 0x61, 0xc0, 0x13, 0x6e, 0x11, 0xda, 0x05, 0x77, 0xe3,
	0x7e, 0x10, 0x25, 0x0c, 0x23, 0x2f, 0x14, 0x9c, 0xe1, 0xfe, 0xdc, 0xb4, 0x6a, 0x9d, 0x1b, 0x02,
	0x9f, 0xd7, 0x55, 0xa2, 0x6d, 0x68, 0x85, 0x71, 0x3f, 0x88, 0x1e, 0xcf, 0xf2, 0x1b, 0x9c, 0xca,
	0xdf, 0x0d, 0x38, 0x0f, 0xa2, 0xbe, 0x88, 0x51, 0xec, 0x79, 0x9c, 0x1f, 0xc4, 0xd8, 0x13, 0x41,
	0xe4, 0xc7, 0x88, 0xcc, 0x4f, 0x2c, 0x42, 0xff, 0xc1, 0xdf, 0x4d, 0xb4, 0x0d, 0xc9, 0x8e, 0xdf,
	0x54, 0x67, 0xf0, 0xff, 0x36, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xb8, 0x06, 0xdf, 0x14, 0x03, 0x00,
	0x00,
}
