// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package simpletracker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserErrorReason int32

const (
	CreateUserErrorReason_USER_ALREADY_EXISTS   CreateUserErrorReason = 0
	CreateUserErrorReason_INTERNAL_SERVER_ERROR CreateUserErrorReason = 1
)

var CreateUserErrorReason_name = map[int32]string{
	0: "USER_ALREADY_EXISTS",
	1: "INTERNAL_SERVER_ERROR",
}

var CreateUserErrorReason_value = map[string]int32{
	"USER_ALREADY_EXISTS":   0,
	"INTERNAL_SERVER_ERROR": 1,
}

func (x CreateUserErrorReason) String() string {
	return proto.EnumName(CreateUserErrorReason_name, int32(x))
}

func (CreateUserErrorReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Success              bool                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorReason          CreateUserErrorReason `protobuf:"varint,2,opt,name=error_reason,json=errorReason,proto3,enum=simpletracker.CreateUserErrorReason" json:"error_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetErrorReason() CreateUserErrorReason {
	if m != nil {
		return m.ErrorReason
	}
	return CreateUserErrorReason_USER_ALREADY_EXISTS
}

func init() {
	proto.RegisterEnum("simpletracker.CreateUserErrorReason", CreateUserErrorReason_name, CreateUserErrorReason_value)
	proto.RegisterType((*CreateUserRequest)(nil), "simpletracker.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "simpletracker.CreateUserResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0x47, 0x8d, 0x07, 0xad, 0xe3, 0x1f, 0xea, 0x4a, 0x31, 0x7a, 0x92, 0xe2, 0x41, 0x3c, 0xe4,
	0xa0, 0x9f, 0x20, 0xe8, 0x20, 0xa5, 0xa5, 0xc2, 0xa4, 0x15, 0x3d, 0x2d, 0x6b, 0x9c, 0x83, 0x68,
	0xb3, 0xeb, 0xcc, 0x86, 0x7e, 0x7d, 0xc9, 0x4a, 0xad, 0x42, 0x8f, 0x8f, 0xdf, 0xdb, 0xc7, 0x32,
	0x00, 0xad, 0xb2, 0x14, 0x41, 0x7c, 0xf4, 0xe6, 0x50, 0xdf, 0x17, 0xe1, 0x93, 0xa3, 0xb8, 0xfa,
	0x83, 0x65, 0x38, 0x86, 0xe3, 0x3b, 0x61, 0x17, 0x79, 0xae, 0x2c, 0xc4, 0x5f, 0x2d, 0x6b, 0x34,
	0xe7, 0xd0, 0xeb, 0x5e, 0x34, 0x6e, 0xc1, 0x79, 0x76, 0x91, 0x5d, 0xed, 0xd1, 0x2f, 0x77, 0x5b,
	0x70, 0xaa, 0x4b, 0x2f, 0x6f, 0xf9, 0xf6, 0xcf, 0xb6, 0xe2, 0xe1, 0x12, 0xcc, 0xdf, 0x98, 0x06,
	0xdf, 0x28, 0x9b, 0x1c, 0x76, 0xb5, 0xad, 0x6b, 0x56, 0x4d, 0xb1, 0x1e, 0xad, 0xd0, 0x3c, 0xc0,
	0x01, 0x8b, 0x78, 0xb1, 0xc2, 0x4e, 0x7d, 0x93, 0x7a, 0x47, 0x37, 0x97, 0xc5, 0xbf, 0x2f, 0x16,
	0xeb, 0x24, 0x76, 0x32, 0x25, 0x97, 0xf6, 0x79, 0x0d, 0xd7, 0x63, 0x18, 0x6c, 0xb4, 0xcc, 0x29,
	0x9c, 0xcc, 0x2b, 0x24, 0x5b, 0x4e, 0x08, 0xcb, 0xfb, 0x17, 0x8b, 0xcf, 0xa3, 0x6a, 0x56, 0xf5,
	0xb7, 0xcc, 0x19, 0x0c, 0x46, 0xd3, 0x19, 0xd2, 0xb4, 0x9c, 0xd8, 0x0a, 0xe9, 0x09, 0xc9, 0x22,
	0xd1, 0x23, 0xf5, 0xb3, 0xd7, 0x9d, 0x74, 0xa8, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0xd4, 0xfd, 0x2f, 0x36, 0x01, 0x00, 0x00,
}
